apiVersion: v1
kind: Secret
metadata:
  name: music-event-core-secrets
  namespace: default
type: Opaque
stringData:
  telegram-bot-token: "7941376949:AAHeus8Bg2E0aydGgWJEvtdOE1S3col-H1M"
  ticketmaster-apikey: "GdnEbnSIzFA31WRk3pvBSC2DhGMCHgHS"