apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-event-core-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music-event-core-app
  template:
    metadata:
      labels:
        app: music-event-core-app
    spec:
      imagePullSecrets:
        - name: dockerhub-secret-music-core
      containers:
        - name: music-event-core-app
          image: vitaliypunko/music-event-core:0.0.3-c4da7e6
          ports:
            - containerPort: 8080
          env:
            # app env
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            # configMap
            - name: TELEGRAM_BOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: music-event-core-config-map
                  key: telegram-bot-username
            - name: TICKETMASTER_PAGE_SIZE
              valueFrom:
                configMapKeyRef:
                  name: music-event-core-config-map
                  key: ticketmaster-page-size
            - name: MUSIC_EVENT_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: music-event-core-config-map
                  key: music-event-auth-url

            # secrets
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: music-event-core-secrets
                  key: telegram-bot-token
            - name: TICKETMASTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: music-event-core-secrets
                  key: ticketmaster-api-key

          resources:
            limits:
              cpu: "0.3"
              memory: "300Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3



---
apiVersion: v1
kind: Service
metadata:
  name: music-event-core-app-service
spec:
  selector:
    app: music-event-core-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
