apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: music-event-core-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    #    - /$2 means “replace the upstream request path with the content
    #   of the second capture group from the regex in path.”
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  ingressClassName: nginx
  rules:
    - host: 66-228-63-42.ip.linodeusercontent.com
      http:
        paths:
          - path: /music-event-core(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: music-event-core-app-service
                port:
                  number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ui-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: 66-228-63-42.ip.linodeusercontent.com
      http:
        paths:
          - path: /kafka-ui
            pathType: Prefix
            backend:
              service:
                name: kafka-ui
                port:
                  number: 80
