apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ2aXRhbGl5cHVua28iLCJwYXNzd29yZCI6ImRja3JfcGF0X3RDUC1uak8wRWpUd1luUVoxN0tXM3BKVUZrWSIsImF1dGgiOiJkbWwwWVd4cGVYQjFibXR2T21SamEzSmZjR0YwWDNSRFVDMXVhazh3UldwVWQxbHVVVm94TjB0WE0zQktWVVpyV1E9PSJ9fX0=
kind: Secret
metadata:
  name: dockerhub-secret-music-core
  namespace: default
type: kubernetes.io/dockerconfigjson

## This code was created by a command in terminal and copied from there
